name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: ./frontend/package.json
          node-version: 16
          pnpm-version: 8
          run_install: true
          cache: true

      - name: Lint code
        run: cd frontend && pnpm run lint

      - name: Run tests
        run: cd frontend && pnpm test 

      - name: Build app
        run: cd frontend && pnpm run build 

      - name: Build Storybook
        run: cd frontend && pnpm run build-storybook